main/urls.py
from django.urls import path
from django.conf import settings

from .views import *

urlpatterns = [
    path('', homepage, name='homepage'),
    path('new_questboard/', new_questboard, name="new_questboard"),
    path('questboards/', all_questboards, name="questboards"),
    path('questboard/<str:slug>', view_questboard, name="view_questboard"),
]

questboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

import re

# Create your models here.
class Questboard(models.Model):
    name = models.CharField(max_length=140, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    required_stars = models.IntegerField(blank=True, null=True)
    slug = models.CharField(max_length=20, null=True, blank=True)
    
    def __str__(self):
        return self.name
    
    def create_slug(self):
        return re.sub('[^A-Za-z0-9 ]+', '', self.name).replace(' ', '-').lower()
     
    def save(self, *args, **kwargs):
        self.slug = self.create_slug()
        super(Questboard, self).save(*args, **kwargs)

class Quest(models.Model):
    questboard = models.ForeignKey(Questboard, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=140, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    stars = models.IntegerField(blank=True, null=True)
    slug = models.CharField(max_length=140, null=True, blank=True)
    is_for_everyone = models.BooleanField(default=False)
    slots = models.IntegerField(blank=True, null=True, default=0)
    
    def __str__(self):
        return self.name
    
    def create_slug(self):
    	return re.sub('[^A-Za-z0-9 ]+', '', self.name).replace(' ', '-').lower()
 
    def save(self, *args, **kwargs):
        self.slug = self.create_slug()
        super(Quest, self).save(*args, **kwargs)
                
                
class Slot(models.Model):
    quest = models.ForeignKey(Quest, on_delete=models.CASCADE, null=True)
    student = models.CharField(max_length=255, blank=True, null=True)
    slot_position = models.IntegerField(blank=True, null=True)
    
    def __str__(self):
        return self.student
    
    

main/forms.py
from django import forms
from .models import *

class QuestboardForm(forms.Form):
    name = forms.CharField(label="Questboard name",max_length=140,
                          widget= forms.TextInput
                           (attrs={'class':'form-control mb-3'}))
    description = forms.CharField(label="Description",
                          widget= forms.Textarea
                           (attrs={'class':'form-control mb-3'}))
    required_stars = forms.IntegerField(label="Required stars", 
                                        min_value=1, max_value=40,  
                                        widget= forms.NumberInput
                           (attrs={'class':'form-control mb-3'}))
    
    class Meta:
        model = Questboard
        fields = ['name', 'description', 'required_stars']
        
class QuestForm(forms.Form):
    name = forms.CharField(label="Quest name",max_length=140,
                          widget= forms.TextInput
                           (attrs={'class':'form-control mb-3'}))
    description = forms.CharField(label="Description",
                          widget= forms.Textarea
                           (attrs={'class':'form-control mb-3'}))
    stars = forms.IntegerField(label="Stars", min_value=1, max_value=7, 
                               widget= forms.NumberInput
                           (attrs={'class':'form-control mb-3'}))
    is_for_everyone = forms.BooleanField(label="Is the quest for everyone? (tick the box if yes):", 
                                         required=False)
    slots = forms.IntegerField(label="Number of slots", required=False, 
                               min_value=0, max_value=7, 
                               widget= forms.NumberInput
                           (attrs={'class':'form-control mb-3'}))
            
    class Meta:
        model = Questboard
        fields = ['name', 'description', 'stars', 'is_for_everyone', 'slots']

main/views.py
from django.shortcuts import render, redirect

from .forms import QuestboardForm, QuestForm
from .models import Questboard, Quest, Slot

# Create your views here.
def homepage(response):
    return render(response, "pages/homepage.html", {})

def all_questboards(response):
    qb = Questboard.objects.all()
    context = {
        'questboards': qb
    }
    return render(response, "pages/questboard/questboards.html", context)


def new_questboard(response):
    if response.method == 'POST': 
        form = QuestboardForm(response.POST)
        if form.is_valid():
            qb = Questboard()
            qb.name = form.cleaned_data['name']
            qb.description = form.cleaned_data['description']
            qb.required_stars = form.cleaned_data['required_stars']
            qb.save()
            return redirect('view_questboard', slug=qb.slug)
    else:
        form = QuestboardForm()
    
    context = {
        'form': form,
    }
    return render(response, "pages/questboard/new_questboard.html", context)


def view_questboard(response, slug):
    qb = Questboard.objects.get(slug=slug)
    
    if response.method == 'POST':
        quest_form = QuestForm(response.POST)
        if response.POST.get('update'):
            qb.name = response.POST.get('qbName')
            qb.description = response.POST.get('qbDescription')
            qb.required_stars = response.POST.get('required_stars')
            qb.save()
            return redirect('view_questboard', slug=qb.slug)
        
        elif quest_form.is_valid() and response.POST.get('addQuest'):
            quest = Quest()
            quest.questboard = qb
            quest.name = quest_form.cleaned_data['name']
            quest.description = quest_form.cleaned_data['description']
            quest.stars = response.POST.get('stars')
            quest.is_for_everyone = quest_form.cleaned_data['is_for_everyone']
            quest.slots = response.POST.get('slots')
            quest.save()
            return redirect('view_questboard', slug=qb.slug)
        
        elif response.POST.get('addSlot'):
            q = Quest.objects.get(id=response.POST.get('quest_id'))
            print(q)
            for s in range(1, q.slots):
                slot = Slot()
                if response.POST.get(q.slug + '-slot' + str(s)):
                    slot.quest = q
                    slot.student = response.POST.get(q.slug + '-slot' + str(s))
                    slot.slot_position = s
                    slot.save()
            return redirect(f'/questboard/{qb.slug}#{q.slug}')
        
        elif response.POST.get('updateQuest'):
            q = Quest.objects.get(id=response.POST.get('edit_id'))
            q.name = response.POST.get('qName_'+str(q.id))
            q.description = response.POST.get('qDescription_'+str(q.id))
            q.stars = response.POST.get('qStars_'+str(q.id))
            q.is_for_everyone = True if response.POST.get('qIsForEveryone_'+str(q.id)) == "on" else False
            q.slots = response.POST.get('qSlots_'+str(q.id))
            q.save()
            return redirect('view_questboard', slug=qb.slug)
                
    else:
        quest_form = QuestForm()
        
    quests = Quest.objects.filter(questboard_id=qb.id)
    slots = []
    for q in quests:
        slot = Slot.objects.filter(quest_id=q.id)
        slots.append({q.id:[{s.slot_position:s.student} for s in slot]})
    
    context = {
        'questboard': qb,
        'quest_form':quest_form,
        'quests': quests,
        'slots': slots
    }
    return render(response, "pages/questboard/questboard.html", context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    {% block stylesheets %}{% endblock stylesheets %}
    <title>{% block title %} {% endblock %} | Questboard </title>
    
</head>
<body>
    <header class= "site-header">
        {% include 'partials/_navbar.html' %}
    </header>
    <div class="header-spacer"></div>
    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main>
    <footer class="site-footer container">
        {% include 'partials/_footer.html' %}
    </footer>
    <script src="{% static 'js/script.js' %}" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/pages/homepage.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/homepage.css' %}">
{% endblock stylesheets %}

{% block title %} Home {% endblock %} 

{% block content %}
<div class="jumbotron">
    <h1 class="display-4">Welcome to Questboard!</h1>
    <p class="lead">
        Create different questboards filled with fun quests to do.
    </p>
    <hr class="my-4">
    <div>
        <a class="btn btn-primary btn-lg" href="{% url 'new_questboard' %}" role="button">
            Create Questboard
        </a>
        <a class="btn btn-secondary btn-lg" href="{% url 'questboards' %}" role="button">
            View all Questboards
        </a>
    </div>
  </div>
{% endblock %}

templates/pages/questboard/new_questboard.html
{% extends "base.html" %}
{% load static %}

{% block title %} New Questboard {% endblock %} 

{% block content %}
<h3>New Questboard</h3>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

templates/pages/questboard/questboard.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'css/questboard.css' %}">
{% endblock stylesheets %}

{% block title %} {{questboard.name}} {% endblock %} 

{% block content %}

<a href="{% url 'questboards' %}" class="d-block mb-2">Back to questboards</a>

<div class="jumbotron">
    <h1 class="display-4">{{ questboard.name}} questboard</h1>
    <p class="lead">
        {{ questboard.description }}
    </p>
    <hr class="my-4">
    <p>
        Each group should collect {{ questboard.required_stars }} to fulfill the
        requirements for {{ questboard.name }}.
    </p>
    <p>
        Call dibs on a quest by appending the names of your group members in the dibs pane: Each quest has a max amount of dibs it can accommodate.
    </p>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addQuestModal">
        Add Quest
    </button>
    <button type="button" class="btn btn-outline-secondary float-right btn-sm" data-toggle="modal" data-target="#editQBModal">
        Edit Questboard
    </button>
</div>

{% include 'partials/_quests.html' %}

<div class="modal fade" id="addQuestModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <form class="modal-content" method="POST">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Add Quest</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="addQuestForm"> 
            {{quest_form.as_p}}
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" name="addQuest" value="addQuest">Add</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
</div>

<div class="modal fade" id="editQBModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <form class="modal-content" method="POST">
        {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalCenterTitle">Edit Questboard details</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body"> 
            <div class="form-group">  
                <label class="col-form-label">Questboard name:</label>  
                <input 
                name="qbName"
                type="text" 
                class="form-control" 
                value="{{ questboard.name }}" />  
            </div>
            
            <div class="form-group">  
                <label class="col-form-label">Description:</label>  
                <textarea 
                    class="form-control" 
                    rows="3" 
                    value="{{questboard.description}}"
                    name="qbDescription"
                >{{ questboard.description }}</textarea>
            </div>

            <div class="form-group">  
                <label class="col-form-label">Required stars:</label>  
                <input 
                name="required_stars"
                type="number" 
                class="form-control" 
                min="1"
                max="40"
                value="{{ questboard.required_stars }}" />  
            </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary" name="update" value="update">Update</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </form>
    </div>
</div>
{% endblock %}

templates/pages/questboard/questboards.html
{% extends "base.html" %}
{% load static %}

{% block title %} Questboard list {% endblock %} 

{% block content %}
<h3>Questboard list</h3>
{% if questboards %}
<ul class="list-group">
    {% for qb in questboards %}
    <li class="list-group-item">
        <div class="row">
            <div class="col-8">
                <h4>{{ qb.name }}</h4>
                <p>
                    {{ qb.description }}
                </p>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-end">
                <a href="{% url 'view_questboard' slug=qb.slug %}" class="btn btn-primary">
                    View questboard
                </a>
            </div>
        </div>
    </li>
    
    {% endfor %}
  </ul>
{% else %}
<h2 class="mb-2">No questboards available</h2>
<a class="btn btn-primary btn-lg" href="{% url 'new_questboard' %}" role="button">
    Create a Questboard
</a>
{% endif %}
{% endblock %}

templates/partials/_footer.html
<div>
    <p class="py-4 text-muted">Created by Miggy Pinaroc for the CSCI 40 Final Project</p>
</div>

templates/partials/_navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Questboard!</a>
    </div>
</nav>

templates/partials/_quests.html
{% if quests %}
{% for q in quests %}
    {% if forloop.first %}<div class="row">{% endif %}
    <div class="col-md-4">
        <div class="card mb-4
        {% if q.stars == 1%}
        border-info
        {% elif q.stars == 2 %}
        border-success
        {% elif q.stars == 3 %}
        border-primary
        {% elif q.stars == 4 %}
        border-warning
        {% else %}
        border-danger
        {% endif %}" id="{{q.slug}}">
            <div class="card-header text-light d-flex justify-content-between align-items-center
            {% if q.stars == 1%}
            bg-info
            {% elif q.stars == 2 %}
            bg-success
            {% elif q.stars == 3 %}
            bg-primary
            {% elif q.stars == 4 %}
            bg-warning
            {% else %}
            bg-danger
            {% endif %}">
                
                <h4>{{ q.name }}</h4>
                
                {% for slot in slots %}
                    {% for item in slot.items %}
                        {% if item.0 == q.id and not item.1%}  
                        <button type="button" class="btn btn-secondary btn-sm mt-2" data-toggle="modal" data-target="#editQuestModal{{q.id}}">
                            Edit
                        </button>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>
            <div class="card-body">
                <div class="card-desc-min-height d-flex justify-content-start align-items-center">
                    <p class="card-text mb-5">
                        {{ q.description }}
                    </p>
                </div>
                <div class="row card-dibs-min-height">
                    <div class="col-lg-3">
                        <b>Dibs</b>
                    </div>
                    <div class="col-lg-9">
                        {% if q.slots %}
                        <form method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="quest_id" id="quest_id" value="{{q.id}}">
                            {% with ''|center:q.slots as range %}
                            {% for _ in range %}
                            <div class="input-group input-group-sm mb-2">
                                <div class="input-group-prepend">
                                  <span class="input-group-text">{{forloop.counter}}.</span>
                                </div>
                            
                                <input 
                                name="{{q.slug}}-slot{{forloop.counter}}"
                                type="text" 
                                class="form-control form-control-sm" 
                                id="{{q.slug}}-slot{{forloop.counter}}" 
                                {% with counter=forloop.counter %}
                                {% for slot in slots %}
                                    {% for item in slot.items %}
                                        {% if item.0 == q.id%}
                                            {% for students in item.1 %}
                                                {% for student in students.items %}
                                                    {% if student.0 == counter%}
                                                    value="{{student.1}}" disabled
                                                    {% endif %}
                                                {% endfor %}
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                                {% endwith %}
                                />
                              </div>
                            
                            {% endfor %}
                            {% endwith %}
                            <button type="button" class="btn btn-outline-primary btn-sm float-right mt-2" data-toggle="modal" data-target="#confirmModal{{forloop.counter}}">
                                Submit
                            </button>
  
                            <div class="modal fade" id="confirmModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Confirm slot</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    </div>
                                    <div class="modal-body">
                                        <p class="lead">Are you sure with your quest choice?</p>
                                        <p class="text-muted"><small>Students cannot retract their dibs once they have confirmed it</small></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary" name="addSlot" value="addSlot">Yes</button>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </form>
                        {% else %}
                        <p class="lead">
                            All students will participate in this quest
                        </p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="card-footer text-center text-warning">
                <div class="card-text mb-3">
                    {% with ''|center:q.stars as range %}
                    {% for _ in range %}
                    <i class="fas fa-star"></i>
                    {% endfor %}
                    {% endwith %}
                </div>
                <small class="text-muted text-center">
                    Copy this link to share quest: {{ request.build_absolute_uri }}#{{q.slug}}
                </small>
            </div>
        </div>
    </div>
    {% if forloop.counter|divisibleby:"3" %}</div><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}

    <div class="modal fade" id="editQuestModal{{q.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form method="POST" class="modal-content">
            {% csrf_token %}
            <input type="hidden" name="edit_id" id="edit_id" value="{{q.id}}">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Edit {{q.name}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="editQuestForm{{q.id}}">
                <p>
                    <label for="id_name">Quest name:</label> 
                    <input type="text" class="form-control mb-3" maxlength="140" name="qName_{{q.id}}" id="qName_{{q.id}}" value="{{q.name}}" />
                </p>
                <p>
                    <label for="id_description">Description:</label> 
                    <textarea name="qDescription_{{q.id}}" cols="40" rows="10" class="form-control mb-3" id="qDescription_{{q.id}}" value="{{q.description}}">{{q.description}}</textarea>
                </p>
                <p>
                    <label for="id_stars">Stars:</label> 
                    <input type="number" name="qStars_{{q.id}}" class="form-control mb-3" min="1" max="7" id="qStars_{{q.id}}" value="{{q.stars}}">
                </p>
                <p>
                    <label for="id_is_for_everyone">Is the quest for everyone? (tick the box if yes):</label> 
                    <input type="checkbox" name="qIsForEveryone_{{q.id}}"  id="qIsForEveryone_{{q.id}}" {% if q.is_for_everyone %}checked{% endif %}>
                </p>
                <p>
                    <label for="id_slots">Number of slots:</label> 
                    <input type="number" name="qSlots_{{q.id}}" class="form-control mb-3" min="0" max="7" id="qSlots_{{q.id}}" value="{{q.slots}}">
                </p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" name="updateQuest" value="updateQuest">Update</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
            </form>
        </div>
    </div>
    <script>
        document.getElementById("qIsForEveryone_{{q.id}}").addEventListener("change", function() {
            if(document.getElementById("qIsForEveryone_{{q.id}}").checked) {
                document.getElementById("editQuestForm{{q.id}}").lastElementChild.style.display = "none";
                document.getElementById("qSlots_{{q.id}}").value = 0;
            } else {
                document.getElementById("editQuestForm{{q.id}}").lastElementChild.style.display = "block";
                document.getElementById("qSlots_{{q.id}}").value = "{{q.slots}}";
            }
        })
    </script>
{% endfor %}
{% else %}
<h1 class="text-center">No quests posted</h1>
{% endif %}